source "https://rubygems.org"

gem "rails", "~> 8.1.1"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"

# ChalkyLayout and dependencies
gem "chalky_layout", path: "../.."
gem "view_component"
gem "slim-rails"
gem "simple_form"

# Pagination
gem "pagy", "~> 9.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]
